version: '3.9'
services:
  database:
    image: "zulip/zulip-postgresql:14"
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - "postgresql-14:/var/lib/postgresql/data:rw"

  memcached:
    image: "memcached:alpine"
    restart: unless-stopped
    command:
      - "sh"
      - "-euc"
      - |
        echo 'mech_list: plain' > "$$SASL_CONF_PATH"
        echo "zulip@$$HOSTNAME:$$MEMCACHED_PASSWORD" > "$$MEMCACHED_SASL_PWDB"
        echo "zulip@localhost:$$MEMCACHED_PASSWORD" >> "$$MEMCACHED_SASL_PWDB"
        exec memcached -S
    environment:
      SASL_CONF_PATH: ${SASL_CONF_PATH}
      MEMCACHED_SASL_PWDB: ${MEMCACHED_SASL_PWDB}
      MEMCACHED_PASSWORD: ${MEMCACHED_PASSWORD}

  rabbitmq:
    image: "rabbitmq:3.12.14"
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - "rabbitmq:/var/lib/rabbitmq:rw"

  redis:
    image: "redis:alpine"
    restart: unless-stopped
    command:
      - "sh"
      - "-euc"
      - |
        echo "requirepass '$$REDIS_PASSWORD'" > /etc/redis.conf
        exec redis-server /etc/redis.conf
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - "redis:/data:rw"

  zulip:
    image: "zulip/docker-zulip:9.3-0"
    restart: unless-stopped
    build:
      context: .
      args:
        ZULIP_GIT_URL: https://github.com/sg12/zulip
        ZULIP_GIT_REF: "9.3"
    ports:
      - "80:80"
      - "443:443"
    environment:
      DB_HOST: ${DB_HOST}
      DB_HOST_PORT: ${DB_HOST_PORT}
      DB_USER: ${DB_USER}
      SSL_CERTIFICATE_GENERATION: ${SSL_CERTIFICATE_GENERATION}
      SETTING_MEMCACHED_LOCATION: ${SETTING_MEMCACHED_LOCATION}
      SETTING_RABBITMQ_HOST: ${SETTING_RABBITMQ_HOST}
      SETTING_REDIS_HOST: ${SETTING_REDIS_HOST}

      SECRETS_email_password: ${SECRETS_email_password}
      SECRETS_rabbitmq_password: ${SECRETS_rabbitmq_password}
      SECRETS_postgres_password: ${SECRETS_postgres_password}
      SECRETS_memcached_password: ${SECRETS_memcached_password}
      SECRETS_redis_password: ${SECRETS_redis_password}
      SECRETS_secret_key: ${SECRETS_secret_key}

      SETTING_EXTERNAL_HOST: ${SETTING_EXTERNAL_HOST}
      SETTING_ZULIP_ADMINISTRATOR: ${SETTING_ZULIP_ADMINISTRATOR}
      SETTING_EMAIL_HOST: ${SETTING_EMAIL_HOST}
      SETTING_EMAIL_HOST_USER: ${SETTING_EMAIL_HOST_USER}
      SETTING_EMAIL_PORT: ${SETTING_EMAIL_PORT}
      SETTING_EMAIL_HOST_PASSWORD: ${SETTING_EMAIL_HOST_PASSWORD}
      SETTING_EMAIL_USE_TLS: ${SETTING_EMAIL_USE_TLS}
      SETTING_ALLOWED_HOSTS: ${SETTING_ALLOWED_HOSTS}

      ZULIP_AUTH_BACKENDS: ${ZULIP_AUTH_BACKENDS}
      ADD_TOKENS_TO_NOREPLY_ADDRESS: ${ADD_TOKENS_TO_NOREPLY_ADDRESS}
      NOREPLY_EMAIL_ADDRESS: ${NOREPLY_EMAIL_ADDRESS}

      ZULIP_SSL_CERTIFICATE: ${ZULIP_SSL_CERTIFICATE}
      ZULIP_SSL_KEY: ${ZULIP_SSL_KEY}
    volumes:
      - "zulip:/data:rw"
      - /opt/zulip-ssl/fullchain.pem:/etc/ssl/certs/zulip.combined-chain.crt:ro
      - /opt/zulip-ssl/privkey.pem:/etc/ssl/private/zulip.key:ro
    ulimits:
      nofile:
        soft: 1000000
        hard: 1048576

volumes:
  zulip:
  postgresql-14:
  rabbitmq:
  redis:
