# Favicon из корня
location = /favicon.ico {
    alias /home/zulip/prod-static/images/favicon.png;
    access_log off;
    add_header Cache-Control "public, max-age=604800, immutable" always;
    expires 7d;
}

# Apple touch icon
location = /apple-touch-icon.png {
    alias /home/zulip/prod-static/images/favicon.png;
    access_log off;
    add_header Cache-Control "public, max-age=604800, immutable" always;
    expires 7d;
}

# Кеширование статичных изображений без хешей (1 день)
location /static/images/ {
    alias /home/zulip/prod-static/images/;
    access_log off;
    add_header Cache-Control "public, max-age=86400" always;
    add_header Access-Control-Allow-Origin * always;
    add_header Timing-Allow-Origin * always;
    try_files $uri =404;
}

# Кеширование audio (1 день)
location /static/audio/ {
    alias /home/zulip/prod-static/audio/;
    access_log off;
    add_header Cache-Control "public, max-age=86400" always;
    try_files $uri =404;
}
